import { Inter } from "next/font/google";
import { Redux } from '../components/Redux'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-screen">
          <Redux>
            {children}
          </Redux>
        </main>
      </body>
    </html>
  );
}
